insert into videos (video_id, title, episode_title)
values (1, 'Russian Terminator', 'Episode 1'),
       (2, 'Aftermath', 'The New Gladiators, Exterminator 2, and The Aftermath'),
       (3, 'Xtro', 'The Killer Eye, They Bite, and Xtro'),
       (4, 'Miami Connection', 'Deadly Prey, Hard Ticket to Hawaii, and Miami Connection'),
       (5, 'Let''s Rap About Fire Safety', 'The Wheel of the Worst'),
       (6, 'R.O.T.O.R.', 'The Vindicator, Cyber Tracker, Robot Jox, and R.O.T.O.R.'),
       (7, 'Thunderpants', 'Playing Dangerous, Shapeshifter, and Thunderpants'),
       (8, 'Gary Coleman For Safety''s Sake', 'Wheel of the Worst #2'),
       (9, 'Gymkata', 'V-World Matrix, The Amazing Bulk, and ????'),
       (10, 'Crazy Fat Ethel II', 'Bloody Birthday, Crazy Fat Ethel II, and Psycho From Texas'),
       (11, 'Skull Forest', 'Night Beast, Trick or Treat, and Skull Forest'),
       (12, 'Incredible Instant Adoring Boyfriend', 'Wheel of the Worst #3'),
       (13, 'The Deadliest Prey', 'Playing Dangerous 2, The Exterminator, and The Deadliest Prey'),
       (14, 'Elves', 'Elves, Santa Claus, and Christmas Vacation 2'),
       (15, 'Yor: The Hunter from the Future', 'Robo-C.H.I.C., Alien Seed, and Yor: The Hunter from the Future'),
       (16, 'The Shoji Tabuchi Show', 'Wheel of the Worst #4'),
       (17, 'Roger Corman''s Fantastic Four',
        'Supergirl, Captain America (1990), and Roger Corman''s Fantastic Four'),
       (18, 'Lethal Ninja', 'Ninja Movies'),
       (19, 'SOS', 'Wheel of the Worst #5'),
       (20, 'Terror in Beverly Hills', 'Ghetto Blaster, Terror in Beverly Hills, and Killing American Style'),
       (21, 'High Voltage', 'High Voltage, Death Spa, and Space Mutiny'),
       (22, 'Beaks: The Movie', 'Shakma, Python II, and Beaks: The Movie'),
       (23, 'How Can I Tell If I''m Really In Love?', 'Wheel of the Worst #6'),
       (24, 'Tammy and the T-Rex', 'Theodore Rex, Carnosaur, Tammy and the T-Rex'),
       (25, 'Blood Lock', 'The Item, The Crawlers, and Blood Lock'),
       (26, 'The Crawlers', 'The Item, The Crawlers, and Blood Lock'),
       (27, 'Dog Sitter', 'Wheel of the Worst #7'),
       (28, 'Alienator', 'Alienator, Alien from the Deep, and Hands of Steel'),
       (29, 'Undefeatable', 'Blood Debts, The Tomb, and Undefeatable'),
       (30, 'Gun Safety with Eddie Eagle', 'Wheel of the Worst #8'),
       (31, 'Low Blow', 'Lady Terminator, Lost in Dinosaur World, and Low Blow'),
       (32, 'Lady Terminator', 'Lady Terminator, Lost in Dinosaur World, and Low Blow'),
       (33, 'Backyard Stunting "Hits & Misses"', 'Wheel of the Worst #9'),
       (34, 'Future War', 'Future War, The Jar, and White Fire'),
       (35, 'Mystics in Bali', 'Kiss Meets the Phantom of the Park, Killer Workout, and Mystics in Bali'),
       (36, 'Double Down', 'The Photon Effect, How I Saved the President, and Double Down'),
       (37, 'Death Wish 3', 'A Very Cannon Christmas'),
       (38, 'Exploding Varmints', 'Wheel of the Worst 10'),
       (39, 'Order of the Black Eagle', 'Order of the Black Eagle, Wired to Kill, and Raiders of Atlantis'),
       (40, 'Double Dragon', 'Plinketto #1'),
       (41, 'How to Get Revenge', 'Wheel of the Worst #11'),
       (42, 'Cyclone', 'Pocket Ninjas, Cyclone, and Dangerous Men'),
       (43, 'Dangerous Men', 'Pocket Ninjas, Cyclone, and Dangerous Men'),
       (44, 'my twinn', 'Wheel of the Worst #12'),
       (45, 'The Skateboard Kid', 'Plinketto #2'),
       (46, 'Parole Violators', 'Parole Violators, Future Force, and Geteven'),
       (47, 'Chopping Mall', 'Scary or Die, Chopping Mall, Exorcist II: The Heretic'),
       (48, 'Safe Crossing: An Egg-cellent Idea', 'Wheel of the Worst 13'),
       (49, 'Johnson Family Christmas Dinner', 'RepliGATOR, Johnson Family Christmas Dinner, and Alligator'),
       (50, 'Space Raiders', 'Episode 48: Plinketto #3'),
       (51, 'The Skateboard Kid 2', 'Carnosaur 2, The Skateboard Kid 2, and Future Zone'),
       (52, 'Slaughter High', 'Biohazard, Slaughter High, and Kill Point'),
       (53, 'Kill Point', 'Biohazard, Slaughter High, and Kill Point'),
       (54, 'Wormania', 'Wheel of the Worst #14'),
       (55, 'Raw Force', 'Bigfoot vs D.B. Cooper, Black Cougar, and Raw Force'),
       (56, 'Hollywood Cop', 'Hollywood Cop'),
       (57, 'Telepathic Communication with Animals', 'Wheel of the Worst #15'),
       (58, 'Empire of the Dark', 'The Sweeper, Empire of the Dark, and Mad Foxes'),
       (59, 'The Last Vampire On Earth', 'The Last Vampire On Earth'),
       (60, 'Turbulence 3: Heavy Metal', 'Plinketto #4'),
       (61, 'Hack-O-Lantern', 'Vampire Assassin, Hack-O-Lantern, and Cathy''s Curse'),
       (62, 'Suburban Sasquatch', 'Suburban Sasquatch'),
       (63, 'Surviving Edged Weapons', 'Wheel of the Worst #16'),
       (64, 'Night of the Kickfighters', 'Merry Kick-mas!'),
       (65, 'Deathstalker II', 'Plinketto #5'),
       (66, 'Partners', 'The Black Spine Edition'),
       (67, 'Faust', 'Hologram Man, Faust, and Blood Street'),
       (68, 'Blood Street', 'Hologram Man, Faust, and Blood Street'),
       (69, 'The Pit', 'Plinketto #6'),
       (70, 'Ryan''s Babe', 'Kill Squad, Ryan''s Babe, and Demonwarp'),
       (71, 'Hug A Tree And Survive Canada', 'Wheel of the Worst #17'),
       (72, 'Celebration of Age: The Croning Ceremony', 'Wheel of the Worst #17'),
       (73, 'Pass Thru', 'Night of the Lepus, Zombie 3, and Silk'),
       (74, 'Lycan Colony', 'Lycan Colony'),
       (75, 'Carnivore', 'Carnivore, HauntedWeen, and Black Roses'),
       (76, 'HauntedWeen', 'Carnivore, HauntedWeen, and Black Roses'),
       (77, 'Black Roses', 'Carnivore, HauntedWeen, and Black Roses'),
       (78, 'Table Manners - Tots to Teens', 'Black Spine Edition #2'),
       (79, 'Quigley', 'Plinketto #7'),
       (80, 'Uninvited', 'Christmas or Cats'),
       (81, 'Cybernator', 'Cybernator, Panther Squad, and Project Metalbeast'),
       (82, 'Creating Rem Lezar', 'Wheel of the Worst #18'),
       (83, 'Action USA', 'Spookies, Action USA, and Alien Private Eye'),
       (84, 'Twister''s Revenge', 'Twister''s Revenge'),
       (85, 'Hostage Officer Survival', 'Episode 78'),
       (86, 'California Big Hunks', 'Black Spine Edition #3'),
       (87, 'ROAR', 'Hawk Jones, Winterbeast, and ROAR'),
       (88, 'Demon Cop', 'Plinketto #8'),
       (89, 'Petey Wheatstraw', 'Petey Wheatstraw'),
       (90, 'Twisted Pair', 'The Instructor, Through Doohan''s Eye, and Twisted Pair'),
       (91, 'Shape Up America', 'Wheel of the Worst #20'),
       (92, 'Rock n'' Roll Nightmare', 'Jack-O, Rock n'' Roll Nightmare, and Shark Exorcist'),
       (93, 'Santa Claws', 'A Very Scary Christmas'),
       (94, 'Wicked World', 'Wicked World'),
       (95, 'If You Love, Show Me', 'Black Spine Junka 2'),
       (96, 'Robot In The Family', 'Showdown, Robot in the Family, and Bloodz vs. Wolvez'),
       (97, 'Computer Beach Party', 'Bad Movie Scavenger Hunt'),
       (98, 'Meredith Monk Turtle Dreams', 'Wheel of the Worst #21'),
       (99, 'How To Host A Princess Party', 'Wheel of the Worst #21'),
       (100, 'American Rickshaw', 'Twin Dragon Encounter, American Rickshaw, and Infested'),
       (101, 'The Satan Killer', 'Shock Em Dead, Hollow Gate, and The Satan Killer'),
       (102, 'Ben and Arthur', 'Ben and Arthur'),
       (103, 'Second Chance vs Magnum Force', 'Christmas 2020'),
       (104, 'Dungeon Master', 'Plinketto #9'),
       (105, 'Blood Shack (aka The Chooper)', 'Blood Shack (aka The Chooper)'),
       (106, 'LA Wars', 'LA Wars, Unmasking the Idol, and Robowoman'),
       (107, 'Fateful Findings', 'Wheel of the Black Spine Plinketto'),
       (108, 'Honorable Men', 'A*P*E, Easy Kill, and Honorable Men'),
       (109, 'T-Bone''s World of Clowning', 'Wheel of the Worst #22'),
       (110, 'Spiral Fitness', 'Wheel of the Worst #22'),
       (111, 'Tartarus', 'Dragon Hunt, Tartarus, and Born into Mafia'),
       (112, 'Milton Berle''s Low Impact High Comedy Workout', 'Black Spine Raffle'),
       (113, 'Don''t Panic', 'Halloween Spooktacular 2021'),
       (114, 'New York Ninja', 'New York Ninja'),
       (115, 'Forklift Safety', 'Christmas 2021'),
       (116, 'William Wegman''s Fay''s 12 Days of Christmas', 'Christmas 2021'),
       (117, 'Starship', 'Blindfold Picks!'),
       (118, 'High Impact Hand Safety', 'Wheel of the Worst #23'),
       (119, 'Stone Cold', 'Plinketto #10'),
       (120, 'Clash in the College', 'Clash in the College'),
       (121, 'Street Smarts - Straight Talk for Kids, Teens & Parents with Detective J.J. Bittenbinder',
        'Black Spine Junka 3'),
       (122, 'Silk 2', 'Bad Movie Scavenger Hunt Too'),
       (123, 'Blood Freak', 'Bad Movie Scavenger Hunt Too'),
       (124, 'Evil Toons', 'Halloween 2022'),
       (125, 'Cyborg', 'Cyborg and Arcade (Albert Pyun Double Feature)'),
       (126, 'Arcade', 'Cyborg and Arcade (Albert Pyun Double Feature)'),
       (127, 'Breakin'' 2: Electric Boogaloo', 'A Very Cannon Christmas II'),
       (128, 'Strong Against Crime', 'Wheel of the Worst #24'),
       (129, 'After Last Season', 'After Last Season'),
       (130, 'Fight of Fury', 'New Releases!'),
       (131, 'Slaughter Day', 'Hawk the Slayer and THE ACTOR FROM MALCOLM IN THE MIDDLE with the X-Ray Eyes'),
       (132, 'A Woman''s Guide to Firearms', 'Wheel of the Worst #25'),
       (133, 'Back in Action', 'Back in Action vs. Enemy Territory'),
       (134, 'Actar 9-11 Infantry', 'Wheel of the Worst #26'),
       (135, 'Vampire Riders', 'Halloween 2023'),
       (136, 'Mammoth Caves Auction', 'Junka 4'),
       (137, 'Wish Upon', 'Wish Upon'),
       (138, 'Mee Christmas', 'Christmas Plinketto'),
       (139, 'Glenn Danzig''s Death Rider in the House of Vampires',
        'Glenn Danzig''s Death Rider in the House of Vampires'),
       (140, 'Lyme Disease - Time for Truth', 'Wheel of the Worst #27'),
       (141, 'Bible Baby', 'Wheel of the Worst #27'),
       (142, 'Cade: The Tortured Crossing', 'Cade: The Tortured Viewing'),
       (143, 'The Baby', 'Battle of the Genres'),
       (144, 'Cranio-Sacral Therapy - The 10 Step Protocol', 'Wheel of the Worst #28'),
       (145, 'Vampire Cop', 'Donald Farmer''s Market'),
       (146, 'Devil Story', 'Halloween Spooktacular 2024'),
       (147, 'Science Crazed', 'Christmas Wheel of the Worst'),
       (148, 'Carnival in Rio', 'Wheel of the Worst #29')
on conflict do nothing
;

insert into tags (tag_id, text, color)
values (1, '🔄 Wheel of the Worst', '#77bb41'),
       (2, '🇨🇦 Colin and/or Jim from Canada', '#d80621'),
       (3, '🎃 Halloween Spooktacular', '#ff6600'),
       (4, '🥈 Sequel', '#341253'),
       (5, '🎅 Christmas', '#009933'),
       (6, '🥷 Len Kabasinski', '#121212'),
       (7, '🍾 Cameron Mitchell', '#34de53'),
       (8, '⚔️ Battle of the Genres', '#dede1f'),
       (9, '🎀 2-Way Tie', '#1567de'),
       (10, '🐢 Freddie Williams', '#986532'),
       (11, '🚗 Leo Fong', '#af33dd'),
       (12, '👽 Neil Breen', '#3781ad'),
       (13, '🏠 Mr McCulkin', '#128982'),
       (14, '🎳 Plinketto', '#583ade'),
       (15, '🔦 Spotlight', '#461aa9'),
       (16, '🕶️ Vitaliy Versace', '#bbcc33'),
       (17, '👣 Dave Wascavage', '#eed3f4'),
       (18, '📼 Black Spine', '#212121'),
       (19, '⏳ Monique Gabrielle', '#f8a492'),
       (20, '👶 Jack Quaid', '#eeccaa'),
       (21, '🖖 Marina Sirtis', '#de23c4')
on conflict do nothing
;

insert into tags_on_videos (video_id, tag_id)
values
    -- Wheel of the Worst
    (5, 1),
    (8, 1),
    (12, 1),
    (16, 1),
    (19, 1),
    (23, 1),
    (27, 1),
    (30, 1),
    (33, 1),
    (38, 1),
    (41, 1),
    (44, 1),
    (48, 1),
    (54, 1),
    (57, 1),
    (63, 1),
    (71, 1),
    (72, 1),
    (82, 1),
    (85, 1),
    (91, 1),
    (107, 1),
    (109, 1),
    (110, 1),
    (118, 1),
    (128, 1),
    (132, 1),
    (134, 1),
    (140, 1),
    (141, 1),
    (144, 1),
    (147, 1),
    -- Colin / Jim
    (9, 2),
    (20, 2),
    (23, 2),
    (31, 2),
    (33, 2),
    (44, 2),
    (46, 2),
    (57, 2),
    (71, 2),
    (72, 2),
    (90, 2),
    (133, 2),
    (134, 2),
    -- Halloween
    (11, 3),
    (25, 3),
    (26, 3),
    (35, 3),
    (47, 3),
    (61, 3),
    (75, 3),
    (76, 3),
    (77, 3),
    (92, 3),
    (101, 3),
    (113, 3),
    (124, 3),
    (135, 3),
    (146, 3),
    -- Sequel
    (13, 4),
    (51, 4),
    (111, 4),
    -- Christmas
    (14, 5),
    (37, 5),
    (49, 5),
    (64, 5),
    (80, 5),
    (93, 5),
    (103, 5),
    (115, 5),
    (116, 5),
    (127, 5),
    (138, 5),
    (147, 5),
    -- Len Kabasinski
    (11, 6),
    (18, 6),
    (55, 6),
    -- Cameron Mitchell
    (20, 7),
    (31, 7),
    (53, 7),
    (55, 7),
    -- Battle of the Genres
    (21, 8),
    (34, 8),
    (83, 8),
    (143, 8),
    -- 2-way tie
    (25, 9),
    (26, 9),
    (31, 9),
    (32, 9),
    (42, 9),
    (43, 9),
    (52, 9),
    (53, 9),
    (71, 9),
    (72, 9),
    (98, 9),
    (99, 9),
    (115, 9),
    (116, 9),
    (122, 9),
    (123, 9),
    (140, 9),
    (141, 9),
    -- Freddie Williams
    (27, 10),
    (52, 10),
    (53, 10),
    (81, 10),
    (128, 10),
    -- Leo Fong
    (31, 11),
    (53, 11),
    (68, 11),
    -- Neil Breen
    (36, 12),
    (73, 12),
    (90, 12),
    (107, 12),
    (142, 12),
    -- Macauly Culkin
    (79, 13),
    (85, 13),
    (87, 13),
    (93, 13),
    (95, 13),
    (136, 13),
    -- Plinketto
    (40, 14),
    (45, 14),
    (50, 14),
    (60, 14),
    (65, 14),
    (69, 14),
    (79, 14),
    (88, 14),
    (104, 14),
    (107, 14),
    (119, 14),
    (138, 14),
    -- Spotlight
    (56, 15),
    (59, 15),
    (62, 15),
    (74, 15),
    (84, 15),
    (89, 15),
    (94, 15),
    (102, 15),
    (105, 15),
    (114, 15),
    (120, 15),
    (125, 15),
    (126, 15),
    (129, 15),
    (137, 15),
    (139, 15),
    (142, 15),
    -- Dave Wascavage
    (62, 17),
    (111, 17),
    -- Black Spine
    (66, 18),
    (78, 18),
    (86, 18),
    (95, 18),
    (103, 18),
    (107, 18),
    (112, 18),
    (121, 18),
    (136, 18),
    -- Monique Gabrielle
    (65, 19),
    (122, 19),
    (124, 19),
    -- Jack Quaid
    (119, 20),
    (146, 20),
    -- Marina Sirtis
    (37, 21),
    (135, 21)
on conflict do nothing
;