spring.application.name=bobotw.com
logging.level.sql=TRACE
logging.level.web=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.data.jdbc.repository=DEBUG
spring.mvc.log-request-details=true
