spring.application.name=bobotw.com
logging.level.sql=TRACE
logging.level.web=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false