create table videos
(
    id            integer       not null generated by default as identity,
    title         varchar(1000) not null,
    episode_title varchar(1000) not null,

    primary key (id)
);

create table rankers
(
    id uuid not null,

    primary key (id)
);

create table pair_rankings
(
    id        integer not null generated by default as identity,
    ranker_id uuid    not null references rankers (id),
    winner_id integer not null references videos (id),
    loser_id  integer not null references videos (id),

    unique (ranker_id, winner_id, loser_id),
    check (winner_id <> loser_id),
    primary key (id)
);

create index rank_winners on pair_rankings (winner_id);
create index rank_losers on pair_rankings (loser_id);
create index rank_rankers on pair_rankings (ranker_id);

create view win_ratios as
with wins as (select winner_id as video_id,
                     count(1)  as wins
              from pair_rankings
              group by winner_id),
     losses as (select loser_id as video_id
                     , count(1) as losses
                from pair_rankings
                group by loser_id)
select videos.id                                           as video_id
     , coalesce(wins.wins, 0)                              as wins
     , coalesce(losses.losses, 0)                          as losses
     , coalesce(wins.wins, 0) + coalesce(losses.losses, 0) as appearances
     , case
           when wins.wins is not null and losses.losses is not null
               then cast(wins.wins as double) / (wins.wins + losses.losses)
           when wins.wins is not null and losses.losses is null then 1.0
           when wins.wins is null and losses.losses is not null then 0.0
           when wins.wins is null and losses.losses is null then 0.0
    end                                                    as win_ratio
from videos
         left outer join wins on videos.id = wins.video_id
         left outer join losses on videos.id = losses.video_id
;

create view videos_with_win_ratios as
select v.id
     , v.title
     , v.episode_title
     , wr.win_ratio
     , wr.appearances
from videos v
         join win_ratios wr on v.id = wr.video_id
;