create table if not exists videos
(
    id            integer       not null generated by default as identity,
    title         varchar(1000) not null,
    episode_title varchar(1000) not null,

    primary key (id)
);

create table if not exists tags
(
    id    integer      not null generated by default as identity,
    text  varchar(100) not null,
    color varchar(7)   not null,

    primary key (id)
);

create table if not exists tags_on_videos
(
    id       integer not null generated by default as identity,
    video_id integer not null references videos (id),
    tag_id   integer not null references tags (id),

    unique (video_id, tag_id)
);

create table if not exists rankers
(
    id uuid not null,

    primary key (id)
);

create table if not exists pair_rankings
(
    id        integer not null generated by default as identity,
    ranker_id uuid    not null references rankers (id),
    winner_id integer not null references videos (id),
    loser_id  integer not null references videos (id),

    unique (ranker_id, winner_id, loser_id),
    check (winner_id <> loser_id),
    primary key (id)
);

create index if not exists rank_winners on pair_rankings (winner_id);
create index if not exists rank_losers on pair_rankings (loser_id);
create index if not exists rank_rankers on pair_rankings (ranker_id);

create or replace view wins as
select winner_id as video_id,
       count(1)  as wins
from pair_rankings
group by winner_id
;

create or replace view losses as
select loser_id as video_id
     , count(1) as losses
from pair_rankings
group by loser_id
;

create or replace view win_ratios as
select videos.id                                           as video_id
     , coalesce(wins.wins, 0)                              as wins
     , coalesce(losses.losses, 0)                          as losses
     , coalesce(wins.wins, 0) + coalesce(losses.losses, 0) as appearances
     , case
           when wins.wins is not null and losses.losses is not null
               then cast(wins.wins as float) / (wins.wins + losses.losses)
           when wins.wins is not null and losses.losses is null then 1.0
           when wins.wins is null and losses.losses is not null then 0.0
           when wins.wins is null and losses.losses is null then 0.0
    end                                                    as win_ratio
from videos
         left outer join wins on videos.id = wins.video_id
         left outer join losses on videos.id = losses.video_id
;

create or replace view videos_with_confidence_bounds as
select v.id
     , v.title
     , v.episode_title
     , wr.appearances
     , case
           when wr.appearances > 0 then
               -- https://www.evanmiller.org/how-not-to-sort-by-average-rating.html
               ((wr.wins + 1.9208) / wr.appearances -
                1.96 * sqrt((wr.wins * wr.losses) / wr.appearances + 0.9604) /
                wr.appearances) / (1 + 3.8416 / wr.appearances)
           else
               0
    end as confidence_lower_bound
from videos v
         join win_ratios wr on v.id = wr.video_id
order by wr.appearances + random() desc
;
